typedef Layers<
    ColorSelect<
        IntArg<STYLE_OPTION_ARG, 0>,
        TrInstant,
        Mix<HoldPeakF<SwingSpeed<400>,
                      Scale<SwingAcceleration<>, Int<2000>, Int<4000>>,
                      Int<8000>>,
            HumpFlicker<
                RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>,
                Stripes<35000,
                        -200,
                        Mix<Int<14000>,
                            Black,
                            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<24000>,
                            Black,
                            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<28000>,
                            Black,
                            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>>,
                100>,
            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>,
        AudioFlicker<
            BrownNoiseFlicker<
                Mix<SwingSpeed<400>,
                    RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>,
                    Mix<Int<6425>,
                        RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>,
                        White>>,
                Stripes<5000,
                        -300,
                        Mix<Int<7710>,
                            Black,
                            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<25700>,
                            Black,
                            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<1285>,
                            Black,
                            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<16384>,
                            Black,
                            RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>>>,
                300>,
            Mix<Int<6425>, RgbArg<BASE_COLOR_ARG, Rgb<255, 255, 255>>, White>>>,
    TransitionEffectL<
        TrSelect<
            IntArg<IGNITION_POWER_UP_ARG, 0>,
            TrInstant,
            TrConcat<TrJoin<TrDelayX<IgnitionTime<380>>, TrInstant>,
                     RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>,
                     TrFade<1000>>,
            TrConcat<
                TrJoin<TrDelayX<IgnitionTime<380>>, TrInstant>,
                Stripes<
                    3000,
                    -3500,
                    RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>,
                    RandomPerLEDFlicker<
                        Mix<Int<7710>,
                            Black,
                            RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Black>,
                    BrownNoiseFlicker<
                        RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>,
                        Mix<Int<3855>,
                            Black,
                            RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        200>,
                    RandomPerLEDFlicker<
                        Mix<Int<3137>,
                            Black,
                            RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<3855>,
                            Black,
                            RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>>>,
                TrFade<800>>,
            TrConcat<
                TrJoin<TrDelayX<IgnitionTime<380>>, TrInstant>,
                Stripes<5000,
                        -2500,
                        RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>,
                        Mix<Int<7710>,
                            Black,
                            RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<3855>,
                            Black,
                            RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>>,
                TrFade<800>>,
            TrConcat<
                TrInstant,
                AudioFlickerL<RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>,
                TrFade<1200>>>,
        EFFECT_IGNITION>,
    TransitionEffectL<
        TrSelect<
            IntArg<RETRACTION_COOL_DOWN_ARG, 0>,
            TrInstant,
            TrConcat<TrJoin<TrDelayX<RetractionTime<0>>, TrInstant>,
                     RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>,
                     TrFade<1000>>,
            TrConcat<
                TrJoin<TrDelayX<RetractionTime<0>>, TrInstant>,
                Stripes<
                    3000,
                    3500,
                    RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>,
                    RandomPerLEDFlicker<
                        Mix<Int<7710>,
                            Black,
                            RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Black>,
                    BrownNoiseFlicker<
                        RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>,
                        Mix<Int<3855>,
                            Black,
                            RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        200>,
                    RandomPerLEDFlicker<
                        Mix<Int<3137>,
                            Black,
                            RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<3855>,
                            Black,
                            RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>>>>,
                TrFade<800>>,
            TrConcat<
                TrJoin<TrDelayX<RetractionTime<0>>, TrInstant>,
                Stripes<5000,
                        2500,
                        RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>,
                        Mix<Int<7710>,
                            Black,
                            RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>>,
                        Mix<Int<3855>,
                            Black,
                            RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>>>,
                TrFade<800>>>,
        EFFECT_RETRACTION>,
    TransitionEffectL<
        TrConcat<TrJoin<TrDelayX<WavLen<>>, TrWipeIn<200>>,
                 AlphaL<RgbArg<STAB_COLOR_ARG, Rgb<255, 255, 255>>,
                        SmoothStep<IntArg<MELT_SIZE_ARG, 28000>, Int<2000>>>,
                 TrWipe<200>>,
        EFFECT_STAB>,
    TransitionEffectL<
        TrWaveX<RgbArg<BLAST_COLOR_ARG, Rgb<255, 255, 255>>,
                Scale<EffectRandomF<EFFECT_BLAST>, Int<100>, Int<400>>,
                Int<100>,
                Scale<EffectPosition<EFFECT_BLAST>, Int<100>, Int<400>>,
                Scale<EffectPosition<EFFECT_BLAST>, Int<28000>, Int<8000>>>,
        EFFECT_BLAST>,
    AlphaL<
        TransitionEffectL<
            TrSelect<
                Scale<ClashImpactF<>, Int<0>, Int<4>>,
                TrConcat<
                    TrInstant,
                    AlphaL<
                        RgbArg<CLASH_COLOR_ARG, Rgb<255, 255, 255>>,
                        Bump<Scale<BladeAngle<>,
                                   Scale<BladeAngle<0, 16000>,
                                         Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                             Int<-12000>>,
                                         Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                             Int<10000>>>,
                                   Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                       Int<-10000>>>,
                             Scale<ClashImpactF<>, Int<8000>, Int<12000>>>>,
                    TrFadeX<Scale<ClashImpactF<>, Int<200>, Int<600>>>>,
                TrWaveX<RgbArg<CLASH_COLOR_ARG, Rgb<255, 255, 255>>,
                        Scale<ClashImpactF<>, Int<100>, Int<400>>,
                        Int<100>,
                        Scale<ClashImpactF<>, Int<100>, Int<400>>,
                        Scale<BladeAngle<>,
                              Scale<BladeAngle<0, 16000>,
                                    Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                        Int<-12000>>,
                                    Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                        Int<10000>>>,
                              Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                  Int<-10000>>>>,
                TrSparkX<
                    Remap<CenterDistF<Scale<
                              BladeAngle<>,
                              Scale<BladeAngle<0, 16000>,
                                    Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                        Int<-12000>>,
                                    Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                        Int<10000>>>,
                              Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                  Int<-10000>>>>,
                          Stripes<1500,
                                  -3000,
                                  RgbArg<CLASH_COLOR_ARG, Rgb<255, 255, 255>>,
                                  Mix<Int<16384>,
                                      Black,
                                      RgbArg<CLASH_COLOR_ARG,
                                             Rgb<255, 255, 255>>>>>,
                    Int<100>,
                    Scale<ClashImpactF<>, Int<100>, Int<400>>,
                    Scale<
                        BladeAngle<>,
                        Scale<BladeAngle<0, 16000>,
                              Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                  Int<-12000>>,
                              Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                  Int<10000>>>,
                        Sum<IntArg<LOCKUP_POSITION_ARG, 16000>, Int<-10000>>>>,
                TrConcat<TrInstant,
                         RgbArg<CLASH_COLOR_ARG, Rgb<255, 255, 255>>,
                         TrFadeX<Scale<ClashImpactF<>, Int<200>, Int<400>>>>,
                TrConcat<TrInstant,
                         RgbArg<CLASH_COLOR_ARG, Rgb<255, 255, 255>>,
                         TrFadeX<Scale<ClashImpactF<>, Int<300>, Int<500>>>>>,
            EFFECT_CLASH>,
        Scale<ClashImpactF<>, Int<24000>, Int<32768>>>,
    LockupTrL<
        TransitionEffect<
            AlphaMixL<
                Bump<
                    Scale<BladeAngle<>,
                          Scale<BladeAngle<0, 16000>,
                                Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                    Int<-12000>>,
                                Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                    Int<10000>>>,
                          Sum<IntArg<LOCKUP_POSITION_ARG, 16000>, Int<-10000>>>,
                    Scale<SwingSpeed<100>, Int<14000>, Int<18000>>>,
                BrownNoiseFlickerL<RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>,
                                   Int<200>>,
                StripesX<Int<1800>,
                         Scale<NoisySoundLevel, Int<-3500>, Int<-5000>>,
                         Mix<Int<6425>,
                             Black,
                             RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>>,
                         RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>,
                         Mix<Int<12850>,
                             Black,
                             RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>>>>,
            AlphaL<
                AudioFlicker<RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>,
                             Mix<Int<10280>,
                                 Black,
                                 RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>>>,
                Bump<
                    Scale<BladeAngle<>,
                          Scale<BladeAngle<0, 16000>,
                                Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                    Int<-12000>>,
                                Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                    Int<10000>>>,
                          Sum<IntArg<LOCKUP_POSITION_ARG, 16000>, Int<-10000>>>,
                    Int<13000>>>,
            TrJoin<TrDelay<8000>, TrInstant>,
            TrFade<3000>,
            EFFECT_LOCKUP_BEGIN>,
        TrConcat<
            TrJoin<TrDelay<50>, TrInstant>,
            Mix<IsLessThan<ClashImpactF<>, Int<26000>>,
                RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>,
                AlphaL<RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>,
                       Bump<Scale<BladeAngle<>,
                                  Scale<BladeAngle<0, 16000>,
                                        Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                            Int<-12000>>,
                                        Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                            Int<10000>>>,
                                  Sum<IntArg<LOCKUP_POSITION_ARG, 16000>,
                                      Int<-10000>>>,
                            Scale<ClashImpactF<>, Int<20000>, Int<60000>>>>>,
            TrFade<300>>,
        TrConcat<TrInstant,
                 RgbArg<LOCKUP_COLOR_ARG, Rgb<255, 255, 255>>,
                 TrFade<400>>,
        SaberBase::LOCKUP_NORMAL>,
    ResponsiveLightningBlockL<
        Strobe<RgbArg<LB_COLOR_ARG, Rgb<255, 255, 255>>,
               AudioFlicker<RgbArg<LB_COLOR_ARG, Rgb<255, 255, 255>>, Blue>,
               50,
               1>,
        TrConcat<TrInstant,
                 AlphaL<RgbArg<LB_COLOR_ARG, Rgb<255, 255, 255>>,
                        Bump<Int<12000>, Int<18000>>>,
                 TrFade<200>>,
        TrConcat<TrInstant,
                 HumpFlickerL<AlphaL<RgbArg<LB_COLOR_ARG, Rgb<255, 255, 255>>,
                                     Int<16000>>,
                              30>,
                 TrSmoothFade<600>>>,
    LockupTrL<
        AlphaL<RandomPerLEDFlickerL<RgbArg<DRAG_COLOR_ARG, Rgb<255, 255, 255>>>,
               SmoothStep<IntArg<DRAG_SIZE_ARG, 28000>, Int<3000>>>,
        TrConcat<TrJoin<TrDelay<4000>, TrWipeIn<200>>,
                 AlphaL<BrownNoiseFlickerL<
                            RgbArg<DRAG_COLOR_ARG, Rgb<255, 255, 255>>,
                            Int<300>>,
                        SmoothStep<IntArg<DRAG_SIZE_ARG, 28000>, Int<3000>>>,
                 TrFade<4000>>,
        TrFade<300>,
        SaberBase::LOCKUP_DRAG>,
    LockupTrL<
        AlphaL<
            Remap<Scale<RampF, Int<65536>, Int<0>>,
                  StaticFire<Mix<TwistAngle<>,
                                 RgbArg<STAB_COLOR_ARG, Rgb<255, 24, 0>>,
                                 RotateColorsX<
                                     Int<3000>,
                                     RgbArg<STAB_COLOR_ARG, Rgb<255, 24, 0>>>>,
                             Mix<TwistAngle<>,
                                 RotateColorsX<
                                     Int<3000>,
                                     RgbArg<STAB_COLOR_ARG, Rgb<255, 24, 0>>>,
                                 RotateColorsX<Int<3000>,
                                               Mix<Int<12000>,
                                                   Black,
                                                   RgbArg<STAB_COLOR_ARG,
                                                          Rgb<255, 24, 0>>>>>,
                             0,
                             3,
                             5,
                             3000,
                             10>>,
            SmoothStep<IntArg<MELT_SIZE_ARG, 28000>, Int<4000>>>,
        TrConcat<
            TrWipeIn<100>,
            AlphaL<RgbArg<STAB_COLOR_ARG, Rgb<255, 24, 0>>,
                   SmoothStep<IntArg<MELT_SIZE_ARG, 28000>, Int<4000>>>,
            TrJoin<TrDelay<4000>, TrFade<300>>,
            AlphaL<Mix<TwistAngle<>,
                       RgbArg<STAB_COLOR_ARG, Rgb<255, 24, 0>>,
                       RotateColorsX<Int<3000>,
                                     RgbArg<STAB_COLOR_ARG, Rgb<255, 24, 0>>>>,
                   SmoothStep<IntArg<MELT_SIZE_ARG, 28000>, Int<4000>>>,
            TrFade<4000>>,
        TrWipe<200>,
        SaberBase::LOCKUP_MELT>,
    InOutTrL<
        TrSelect<
            IntArg<IGNITION_OPTION_ARG, 0>,
            TrWipeSparkTipX<RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>,
                            IgnitionTime<380>>,
            TrWipeX<Scale<IsLessThan<BladeAngle<>, Int<16000>>,
                          Mult<IgnitionTime<380>, Int<16384>>,
                          IgnitionTime<380>>>,
            TrConcat<TrFadeX<IgnitionTime<380>>,
                     Red,
                     TrFadeX<IgnitionTime<380>>,
                     DarkOrange,
                     TrFadeX<IgnitionTime<380>>,
                     White,
                     TrFadeX<IgnitionTime<380>>>,
            TrConcat<TrWipeInX<Mult<IgnitionTime<380>, Int<6553>>>,
                     RandomBlink<30000,
                                 RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>,
                                 Black>,
                     TrJoin<TrDelayX<Mult<IgnitionTime<380>, Int<19660>>>,
                            TrWipeInX<Mult<IgnitionTime<230>, Int<6553>>>>,
                     Mix<SmoothStep<Scale<SlowNoise<Int<30000>>,
                                          IntArg<EMITTER_SIZE_ARG, 1000>,
                                          Sum<Int<5000>,
                                              IntArg<EMITTER_SIZE_ARG, 1000>>>,
                                    Int<-3000>>,
                         Black,
                         RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>,
                     TrWipeX<Mult<IgnitionTime<380>, Int<19660>>>>,
            TrConcat<TrJoin<TrDelayX<Mult<IgnitionTime<380>, Int<16384>>>,
                            TrWipeX<Mult<IgnitionTime<380>, Int<16384>>>>,
                     Mix<SmoothStep<NoisySoundLevel, Int<-1>>,
                         Black,
                         RgbArg<IGNITION_COLOR_ARG, Rgb<255, 255, 255>>>,
                     TrWipeX<Mult<IgnitionTime<380>, Int<16384>>>>>,
        TrSelect<
            IntArg<RETRACTION_OPTION_ARG, 0>,
            TrWipeInSparkTipX<RgbArg<RETRACTION_COLOR_ARG, Rgb<255, 255, 255>>,
                              RetractionTime<0>>,
            TrWipeInX<Scale<IsLessThan<BladeAngle<>, Int<16000>>,
                            Mult<RetractionTime<0>, Int<16384>>,
                            RetractionTime<0>>>,
            TrConcat<TrFadeX<RetractionTime<0>>,
                     White,
                     TrFadeX<RetractionTime<0>>,
                     DarkOrange,
                     TrFadeX<RetractionTime<0>>,
                     Red,
                     TrFadeX<RetractionTime<0>>>>,
        Black>,
    TransitionEffectL<
        TrSelect<
            IntArg<PREON_OPTION_ARG, 0>,
            TrInstant,
            TrConcat<
                TrInstant,
                AlphaL<
                    Mix<Trigger<EFFECT_PREON,
                                Mult<Int<16384>, WavLen<EFFECT_PREON>>,
                                Mult<Int<10922>, WavLen<EFFECT_PREON>>,
                                Mult<Int<5462>, WavLen<EFFECT_PREON>>>,
                        BrownNoiseFlicker<
                            Black,
                            RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                            100>,
                        RandomPerLEDFlicker<
                            RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                            Rgb<50, 50, 50>>,
                        BrownNoiseFlicker<
                            Mix<NoisySoundLevel,
                                RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                                RotateColorsX<Int<4000>,
                                              RgbArg<PREON_COLOR_ARG,
                                                     Rgb<255, 255, 255>>>>,
                            White,
                            50>>,
                    SmoothStep<Scale<NoisySoundLevel, Int<-10000>, Int<36000>>,
                               Int<-4000>>>,
                TrDelayX<WavLen<EFFECT_PREON>>>,
            TrConcat<
                TrFadeX<Mult<Int<8192>, WavLen<EFFECT_PREON>>>,
                AlphaL<HumpFlickerL<RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                                    10>,
                       SmoothStep<IntArg<PREON_SIZE_ARG, 8192>, Int<-4000>>>,
                TrFadeX<Mult<Int<8192>, WavLen<EFFECT_PREON>>>,
                AlphaL<HumpFlickerL<RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                                    15>,
                       SmoothStep<Sum<Int<2000>, IntArg<PREON_SIZE_ARG, 8192>>,
                                  Int<-4000>>>,
                TrFadeX<Mult<Int<8192>, WavLen<EFFECT_PREON>>>,
                AlphaL<HumpFlickerL<RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                                    20>,
                       SmoothStep<Sum<Int<4000>, IntArg<PREON_SIZE_ARG, 8192>>,
                                  Int<-4000>>>,
                TrBoingX<Mult<Int<8192>, WavLen<EFFECT_PREON>>, 3>>,
            TrConcat<
                TrBoingX<Mult<Int<10922>, WavLen<EFFECT_PREON>>, 5>,
                AlphaL<BrownNoiseFlickerL<
                           RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                           Int<100>>,
                       SmoothStep<IntArg<PREON_SIZE_ARG, 8192>, Int<-4000>>>,
                TrBoingX<Mult<Int<10922>, WavLen<EFFECT_PREON>>, 3>,
                Black,
                TrBoingX<Mult<Int<7260>, WavLen<EFFECT_PREON>>, 3>,
                AlphaL<BrownNoiseFlickerL<
                           RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                           Int<200>>,
                       SmoothStep<Sum<Int<4000>, IntArg<PREON_SIZE_ARG, 8192>>,
                                  Int<-4000>>>,
                TrBoingX<Mult<Int<3664>, WavLen<EFFECT_PREON>>, 3>>,
            TrConcat<TrInstant,
                     AlphaL<BrownNoiseFlickerL<
                                RgbArg<PREON_COLOR_ARG, Rgb<255, 255, 255>>,
                                Int<30>>,
                            SmoothStep<Scale<SlowNoise<Int<2000>>,
                                             IntArg<PREON_SIZE_ARG, 8192>,
                                             Sum<IntArg<PREON_SIZE_ARG, 8192>,
                                                 Int<4000>>>,
                                       Int<-2000>>>,
                     TrDelayX<WavLen<EFFECT_PREON>>>>,
        EFFECT_PREON>,
    TransitionEffectL<
        TrSelect<
            IntArg<OFF_OPTION_ARG, 0>,
            TrInstant,
            TrConcat<
                TrInstant,
                AlphaL<White,
                       SmoothStep<IntArg<PREON_SIZE_ARG, 8192>, Int<-4000>>>,
                TrFadeX<Mult<Scale<IsLessThan<WavLen<EFFECT_POSTOFF>, Int<200>>,
                                   WavLen<EFFECT_POSTOFF>,
                                   Int<4000>>,
                             Int<10923>>>,
                AlphaL<Orange,
                       SmoothStep<IntArg<PREON_SIZE_ARG, 8192>, Int<-4000>>>,
                TrFadeX<Mult<Scale<IsLessThan<WavLen<EFFECT_POSTOFF>, Int<200>>,
                                   WavLen<EFFECT_POSTOFF>,
                                   Int<4000>>,
                             Int<10923>>>,
                AlphaL<Red,
                       SmoothStep<IntArg<PREON_SIZE_ARG, 8192>, Int<-2000>>>,
                TrFadeX<Mult<Scale<IsLessThan<WavLen<EFFECT_POSTOFF>, Int<200>>,
                                   WavLen<EFFECT_POSTOFF>,
                                   Int<4000>>,
                             Int<10923>>>>,
            TrConcat<
                TrInstant,
                AlphaL<BrownNoiseFlickerL<
                           RgbArg<POSTOFF_COLOR_ARG, Rgb<255, 255, 255>>,
                           Int<30>>,
                       SmoothStep<Scale<SlowNoise<Int<2000>>,
                                        IntArg<EMITTER_SIZE_ARG, 2000>,
                                        Sum<IntArg<EMITTER_SIZE_ARG, 2000>,
                                            Int<3000>>>,
                                  Int<-4000>>>,
                TrDelayX<Scale<IsLessThan<WavLen<EFFECT_POSTOFF>, Int<200>>,
                               WavLen<EFFECT_POSTOFF>,
                               Int<4000>>>>>,
        EFFECT_POSTOFF>>
    LARGE_TYPE_WITH_OPTIONS;

